scopes:

    enabled:

        # Filter name
        label: Disabled

        # Filter type
        type: switch

        # SQL Conditions
        conditions:
            - is_enabled = '1'
            - is_enabled = '0'
